<a href="https://colab.research.google.com/github/prasadw350-lang/Assignments/blob/main/Assignment24(T-P).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [121]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

Classification Dataset

In [122]:
filepath = "/content/drive/MyDrive/mushrooms.csv"
cls_df = pd.read_csv(filepath)

cls_df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g


In [123]:
cls_df.info()

cls_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

,0
class,0
cap-shape,0
cap-surface,0
cap-color,0
bruises,0
odor,0
gill-attachment,0
gill-spacing,0
gill-size,0
gill-color,0


In [124]:
le = LabelEncoder()
for col in cls_df.columns:
    cls_df[col] = le.fit_transform(cls_df[col])

In [125]:
X_cls = cls_df.drop("class", axis=1)
y_cls = cls_df["class"]

In [126]:
X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(
    X_cls,
    y_cls,
    test_size=0.2,
    random_state=42
)

In [127]:
scaler_cls = StandardScaler()
X_train_cls = scaler_cls.fit_transform(X_train_cls)
X_test_cls = scaler_cls.transform(X_test_cls)

Regression Dataset

In [128]:
filepath = "/content/drive/MyDrive/insurance.csv"
reg_df = pd.read_csv(filepath)

reg_df.head()


,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [129]:
reg_df.info()

reg_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


,0
age,0
sex,0
bmi,0
children,0
smoker,0
region,0
charges,0


In [130]:
reg_df = pd.get_dummies(reg_df, drop_first=True)

X_reg = reg_df.drop("charges", axis=1)
y_reg = reg_df["charges"]

In [131]:
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

In [132]:
num_cols = ["age", "bmi", "children"]

scaler_reg = StandardScaler()

X_train_reg[num_cols] = scaler_reg.fit_transform(X_train_reg[num_cols])

X_test_reg[num_cols] = scaler_reg.transform(X_test_reg[num_cols])

Clssification Algorithms

In [133]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train_cls, y_train_cls)

lr_pred = lr.predict(X_test_cls)

lr_acc = accuracy_score(y_test_cls, lr_pred)

print("Accuracy:", lr_acc)
print(confusion_matrix(y_test_cls, lr_pred))
print(classification_report(y_test_cls, lr_pred))

Accuracy: 0.952
[[799  44]
 [ 34 748]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.95       843
           1       0.94      0.96      0.95       782

    accuracy                           0.95      1625
   macro avg       0.95      0.95      0.95      1625
weighted avg       0.95      0.95      0.95      1625



In [134]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train_cls, y_train_cls)

dt_pred = dt.predict(X_test_cls)

dt_acc = accuracy_score(y_test_cls, dt_pred)

print("Accuracy:", dt_acc)
print(confusion_matrix(y_test_cls, dt_pred))
print(classification_report(y_test_cls, dt_pred))

Accuracy: 1.0
[[843   0]
 [  0 782]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625



In [135]:
from sklearn.svm import SVC

svm = SVC()

svm.fit(X_train_cls, y_train_cls)

svm_pred = svm.predict(X_test_cls)

svm_acc = accuracy_score(y_test_cls, svm_pred)

print("Accuracy:", svm_acc)
print(confusion_matrix(y_test_cls, svm_pred))
print(classification_report(y_test_cls, svm_pred))

Accuracy: 1.0
[[843   0]
 [  0 782]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625



In [136]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_cls, y_train_cls)

knn_pred = knn.predict(X_test_cls)

knn_acc = accuracy_score(y_test_cls, knn_pred)

print("Accuracy:", knn_acc)
print(confusion_matrix(y_test_cls, knn_pred))
print(classification_report(y_test_cls, knn_pred))

Accuracy: 1.0
[[843   0]
 [  0 782]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       843
           1       1.00      1.00      1.00       782

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625



In [137]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

nb.fit(X_train_cls, y_train_cls)

nb_pred = nb.predict(X_test_cls)

nb_acc = accuracy_score(y_test_cls, nb_pred)

print("Accuracy:", nb_acc)
print(confusion_matrix(y_test_cls, nb_pred))
print(classification_report(y_test_cls, nb_pred))

Accuracy: 0.9218461538461539
[[771  72]
 [ 55 727]]
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       843
           1       0.91      0.93      0.92       782

    accuracy                           0.92      1625
   macro avg       0.92      0.92      0.92      1625
weighted avg       0.92      0.92      0.92      1625



In [150]:
comparison = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "Decision Tree",
        "Support Vector Machine",
        "K-Nearest Neighbors",
        "Naive Bayes"
    ],
    "Accuracy": [
        lr_acc,
        dt_acc,
        svm_acc,
        knn_acc,
        nb_acc
    ]
})

comparison

,Algorithm,Accuracy
0,Logistic Regression,0.952000
1,Decision Tree,1.000000
2,Support Vector Machine,1.000000
3,K-Nearest Neighbors,1.000000
4,Naive Bayes,0.921846


In [139]:
best_cls = comparison_cls.loc[comparison_cls["Accuracy"].idxmax()]

print("Best Classification Model:", best_cls["Algorithm"])
print("Accuracy:", best_cls["Accuracy"])

Best Classification Model: Decision Tree
Accuracy: 1.0


Regression Algorithms

In [140]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

lr_reg = LinearRegression()
lr_reg.fit(X_train_reg, y_train_reg)
lr_pred = lr_reg.predict(X_test_reg)
lr_r2 = r2_score(y_test_reg, lr_pred)

print("R2 Score:", lr_r2)

R2 Score: 0.7835929767120722


In [141]:
from sklearn.tree import DecisionTreeRegressor

dt_reg = DecisionTreeRegressor(random_state=42)
dt_reg.fit(X_train_reg, y_train_reg)
dt_pred = dt_reg.predict(X_test_reg)
dt_r2 = r2_score(y_test_reg, dt_pred)

print("R2 Score:", dt_r2)

R2 Score: 0.7372259788399772


In [142]:
from sklearn.svm import SVR

svr = SVR()
svr.fit(X_train_reg, y_train_reg)
svr_pred = svr.predict(X_test_reg)
svr_r2 = r2_score(y_test_reg, svr_pred)

print("R2 Score:", svr_r2)

R2 Score: -0.07149402790922443


In [143]:
from sklearn.neighbors import KNeighborsRegressor

knn_reg = KNeighborsRegressor(n_neighbors=5)
knn_reg.fit(X_train_reg, y_train_reg)
knn_pred = knn_reg.predict(X_test_reg)
knn_r2 = r2_score(y_test_reg, knn_pred)

print("R2 Score:", knn_r2)

R2 Score: 0.7018603093698963


In [144]:
comparison_reg = pd.DataFrame({
    "Algorithm": [
        "Linear Regression",
        "Decision Tree Regressor",
        "Support Vector Regressor",
        "K-Nearest Neighbors Regressor"
    ],
    "R2 Score": [
        lr_r2,
        dt_r2,
        svr_r2,
        knn_r2
    ]
})

comparison_reg

,Algorithm,R2 Score
0,Linear Regression,0.783593
1,Decision Tree Regressor,0.737226
2,Support Vector Regressor,-0.071494
3,K-Nearest Neighbors Regressor,0.701860


In [145]:
best_reg = comparison_reg.loc[comparison_reg["R2 Score"].idxmax()]

print("Best Regression Model:", best_reg["Algorithm"])
print("R2 Score:", best_reg["R2 Score"])

Best Regression Model: Linear Regression
R2 Score: 0.7835929767120722


Model Selection

In [146]:
import joblib
comparison_cls = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "Decision Tree",
        "Support Vector Machine",
        "K-Nearest Neighbors",
        "Naive Bayes"
    ],
    "Accuracy": [
        lr_acc,
        dt_acc,
        svm_acc,
        knn_acc,
        nb_acc
    ]
})

comparison_cls


,Algorithm,Accuracy
0,Logistic Regression,0.952000
1,Decision Tree,1.000000
2,Support Vector Machine,1.000000
3,K-Nearest Neighbors,1.000000
4,Naive Bayes,0.921846


In [147]:
best_cls = comparison_cls.loc[comparison_cls["Accuracy"].idxmax()]

print("Best Classification Model:", best_cls["Algorithm"])
print("Accuracy:", best_cls["Accuracy"])

Best Classification Model: Decision Tree
Accuracy: 1.0


In [148]:
best_reg = comparison_reg.loc[comparison_reg["R2 Score"].idxmax()]

print("Best Regression Model:", best_reg["Algorithm"])
print("R2 Score:", best_reg["R2 Score"])

Best Regression Model: Linear Regression
R2 Score: 0.7835929767120722


In [149]:
joblib.dump(lr, "Logistic_Regression.pkl")
joblib.dump(dt, "Decision_Tree_Classifier.pkl")
joblib.dump(svm, "SVM_Classifier.pkl")
joblib.dump(knn, "KNN_Classifier.pkl")
joblib.dump(nb, "Naive_Bayes.pkl")

joblib.dump(lr_reg, "Linear_Regression.pkl")
joblib.dump(dt_reg, "Decision_Tree_Regressor.pkl")
joblib.dump(svr, "SVR.pkl")
joblib.dump(knn_reg, "KNN_Regressor.pkl")

joblib.dump(scaler_cls, "Classification_Scaler.pkl")
joblib.dump(scaler_reg, "Regression_Scaler.pkl")

joblib.dump(X_cls.columns.tolist(), "Classification_Columns.pkl")
joblib.dump(X_reg.columns.tolist(), "Regression_Columns.pkl")

['Regression_Columns.pkl']