In [1]:
import numpy as np
# Create a 5x6 array with random integers between 10 and 100
arr = np.random.randint(10, 101, (5, 6))

# Display array properties
print("Array:")
print(arr)
print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array:
[[ 29  51  60  10  96  29]
 [ 95  54  37  16  73  16]
 [100  77  31  30  40  73]
 [ 47  59  12  69  95  24]
 [ 12  68  16  86  40  24]]

Shape: (5, 6)
Size: 30
Data Type: int32
